export const all_items_list=[{"name":"बेसन लाडू" ,"img":"ladu.jpeg","rate":"१६०"},
    {"name":"जिलेबी","img":"jalebi.jpeg","rate":"१६०"},
    {"name":"म्हैसूरपाक","img":"mhaisur_paak.jpeg","rate":"२००"},
    {"name":"गुलाबजामुन","img":"gulabjamun.jpeg","rate":"२००"},
    {"name":"ओली भेळ","img":"oli_bhel.jpeg","rate":"२००"},
    {"name":"फरसाण","img":"fersan_chivda.jpeg","rate":"२००"},
    {"name":"बालूशाही","img":"balushahi.jpg","rate":"१६०"},
    {"name":"खमंग ढोकळा","img":"dhokla.jpg","rate":"१६०"},
    {"name":"खाजा","img":"khaja.jpeg","rate":"१६०"},
    {"name":"खवा बर्फी","img":"khawa_barfi.jpeg","rate":"३००"},
    {"name":"खोबरा  बर्फी","img":"khobra_barfi.jpeg","rate":"३००"},
    {"name":"मलई पेडा","img":"malai_peda.jpeg","rate":"३००"},
    {"name":"खवा पेडा","img":"khawa_peda.jpeg","rate":"३००"},
    {"name":"खुर्मा","img":"khurma.jpeg","rate":"१५०"},
    {"name":"बेसन पापडी","img":"papdi.jpeg","rate":"१६०"},
    {"name":"फराळी चिवडा","img":"nailon_chivda.jpeg","rate":"१६०"},
    {"name":"गाठी शेव","img":"gathi_shev.jpeg","rate":"१६०"},
    {"name":"भाव नगरी (शेवभाजी शेव )","img":"bhav_nagari.jpeg","rate":"१६०"},
    {"name":"शेंगदाणा चक्की ","img":"gul_chakki.jpeg","rate":"१६०"},
    {"name":"शंकरपाळे","img":"shanker_pale.jpeg","rate":"१६०"},
    {"name":"सोनपापडी","img":"sonpapdi.jpeg","rate":"२००"},
    {"name":"रेवडी","img":"revdi1.jpeg","rate":"१६०"},
    {"name":"मुरमुरे","img":"murmura1.jpg","rate":"१००"},
    {"name":"मुरमुरा चिवडा","img":"yellow_murmura.jpeg","rate":"१२०"}]